# Generated by Django 4.1.4 on 2023-02-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('model', models.CharField(default='', max_length=100)),
                ('scale', models.CharField(default='', max_length=100)),
                ('toybrand', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('colortype', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
